import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google"
import "./globals.css";
import { Nav } from "@/components/Navbar";
import { useRef } from "react";

const montserrat = Montserrat({
  weight: ['700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
